export enum Locations {
  alhambra = 'Alhambra Courthouse',
  bellflower = 'Bellflower Courthouse',
  beverlyHills = 'Beverly Hills Courthouse',
  burbank = 'Burbank Courthouse',
  chatsworth = 'Chatsworth Courthouse',
  compton = 'Compton Courthouse',
  glendale = 'Glendale Courthouse',
  governorGeorgeDeukmejian = 'Governor George Deukmejian Courthouse',
  inglewood = 'Inglewood Courthouse',
  metropolitan = 'Metropolitan Courthouse',
  michaelAntonovich = 'Michael D. Antonovich Antelope Valley Courthouse',
  norwalk = 'Norwalk Courthouse',
  pasadena = 'Pasadena Courthouse',
  santaMonica = 'Santa Monica Courthouse',
  springStreet = 'Spring Street Courthouse',
  stanleyMosk = 'Stanley Mosk Courthouse',
  torrance = 'Torrance Courthouse',
  vanNuys = 'Van Nuys Courthouse',
  westCovina = 'West Covina Courthouse',
}
